[tox]
requires =
    tox>=4.11
env_list =
    test
    format-check
    type
[testenv]
base_python = 3.12
set_env = 
    MAX_BUYS = 2
    MAX_SELLS = 2
    POWER = 50
    CAPACITY = 100

[testenv:test]
description = Run unit tests and output coverage report
extras = 
    test
commands =
    pytest {posargs}

[testenv:format-check]
description = Check code is compliant with ruff
skip_install = true
deps = 
    {[testenv:format]deps}
commands = 
    ruff check {posargs}
    ruff format --diff {posargs}
    pyproject-fmt pyproject.toml --check

[testenv:type]
description = Run type checking using mypy
deps = 
    mypy==1.11.0
commands =
    mypy ua_batteries --install-types --non-interactive {posargs}

[testenv:format]
description = Automatically foramt and lint code using ruff
skip_install = true
deps = 
    pyproject-fmt==2.1.4
    ruff==0.5.1
commands = 
    ruff check --fix .
    ruff format .
    pyproject-fmt pyproject.toml
